version: '3'

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ssscientific
      MYSQL_ROOT_PASSWORD: password
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      # PMA_USER: ssscientific_user
      # PMA_PASSWORD: ssscientific@0715
    ports:
      - "8089:80"
    depends_on:
      - db
    networks:
      - my-network
volumes:
  db_data:

networks:
  my-network:
    driver: bridge